development:
  adapter: postgresql
  encoding: unicode
  database: my_app_database
  pool: 5
  username: modet
  password: odnetnin8128   ### password you have specified within psql
  host: localhost
  port: 5432               ### you can configure it in file postgresql.conf
